Feature
guirecordon/tnw-page-mockup pull request #8
Opened 2020-03-14 01:33 UTC by guirecordon

**Responsive Design - Collaborative project:** 

In this project, we build a clone of The Next Web webpage, with a special focus on its responsiveness. We used mainly the CSS grid in our media queries to layout the design. We used a mobile-first approach with breakpoints. Following are some specifications of our project: 

- breaking points at 768px and 1024px;
- background images for most of the articles thumbnails; 
- used gradient for the hero image;
- used 'display: none' to adjust changes to the different screen sizes;
- used CSS flex to align the nav bar, etc.

2020-03-14 03:24 UTC, majovanilla requested changes
Hey team, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

- Good Readme file
- Good Pull Request Message


### Required Changes: ✍️
There are still some changes 👇 you need to implement to approve this request (see comments below) 🔍

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Use semantic HTML in the structure of your HTML file. Favor the use of `<nav>`,  `<main>`,  `<footer>`, to enclose the elements on your file. You are already using nav and footer, just add the main tag to enclose the rest of your elements.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-03-14 03:24 UTC, majovanilla commented on README.md
> +>
Great description!! :+1:

2020-03-14 03:24 UTC, majovanilla commented on index.html
> +  </div>
The three articles in the top section are not showing the images. Check your link.

2020-03-14 03:24 UTC, majovanilla commented on index.html
> +      <h2 class="ln-heading">Latest news <i class="material-icons">keyboard_arrow_right</i></h2>
The articles in the latest news section are not showing the images. Check your links.

2020-03-14 03:24 UTC, majovanilla commented on css/style.css
> +
These images look disproportioned in all screen sizes. Please fix it.

2020-03-14 03:24 UTC, majovanilla commented on index.html
> +          <p><span class="line-through">$6000</span><span> - </span>$39.99</p>
The latest deals section is not displaying the images correctly. Please fix the URL in your CSS.

2020-03-14 03:24 UTC, majovanilla commented on index.html
> +      </ul>
This section is not behaving exactly as the original one in the medium breakpoint. Check the images below, it's just a minor change in the way the subtitles are arranged. Yours look like this:
![Screenshot from 2020-03-13 21-15-17](https://user-images.githubusercontent.com/51926937/76673945-ebcbd200-656f-11ea-9f02-105e4c851a1f.png)

The original is:
![Screenshot from 2020-03-13 21-15-23](https://user-images.githubusercontent.com/51926937/76673953-f7b79400-656f-11ea-9d74-e21627644f4f.png)

2020-03-16 20:50 UTC, pelzolga123 approved these changes
Approved.

2020-03-16 20:50 UTC, pelzolga123 commented
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

2020-03-16 20:58 UTC, merged